### ISSUE TITLE
ERROR: overwrite and append cannot both be TRUE

### ISSUE THREAD

**Issue by burnsal** [jbryer/ShinyQDA#3]
Hello,

We are running into errors on the `qda` function when trying to set up our own ShinyQDA project. We first tried the demo data as written in the documentation:

![Capture](https://github.com/jbryer/ShinyQDA/assets/54477812/8136ed49-c4e5-45c3-94bd-2a2451a85664)

The same error occurs when using the `ShinyQDA::newapp(...)` function on our data or the daacs data. 

Assistance would be greatly appreciated. Thank you!

**Comment by jbryer** [comment]
This has been fixed.
